### ISSUE TITLE
About Fitting on New Datasets

### ISSUE THREAD

**Issue by jeb0813** [YuelangX/Multiview-3DMM-Fitting#1]
Hi Yuelang. 

I followed the instructions and obtained identical results on ```NeRSemble```, but when I tried it on ```MEAD```, the loss starts at around 750 and never converg. 

The preprocess on these two datasets is same, expect the camera params, I got them from colmap (but the cam params in NeRSemble is also from colmap).

 And I have checked the lmds from step 1, seems alright. However, the fitting cannot work. Do you have any idea on that?
 
 Thanks.

**Comment by YuelangX** [comment]
What does the visualization result look like? You can try adjusting the pose and scale initialized in BFMModule.py.

**Comment by jeb0813** [comment]
@YuelangX thanks for quickly response.
The visualization seems fine on both datasets.

In your approach, is the BFM model aligned to the world coordinate system when initialized?
I think this has something to do with the camera's external parameters.

![image_2](https://github.com/YuelangX/Multiview-3DMM-Fitting/assets/57085763/70f85d62-05d5-4ea3-9914-84875ab5c660)
![image_222200036](https://github.com/YuelangX/Multiview-3DMM-Fitting/assets/57085763/31daa045-5abc-4642-92a9-1d3daf3b7844)

**Comment by youngAt19** [comment]
> [@YuelangX](https://github.com/YuelangX) thanks for quickly response. The visualization seems fine on both datasets.
> 
> In your approach, is the BFM model aligned to the world coordinate system when initialized? I think this has something to do with the camera's external parameters.
> 
> ![image_2](https://github.com/YuelangX/Multiview-3DMM-Fitting/assets/57085763/70f85d62-05d5-4ea3-9914-84875ab5c660) ![image_222200036](https://github.com/YuelangX/Multiview-3DMM-Fitting/assets/57085763/31daa045-5abc-4642-92a9-1d3daf3b7844)

hi, could you share how to fixed the fitting? I got the same problem when using my own dataset
