### ISSUE TITLE
what FLAME version did you use?

### ISSUE THREAD

**Issue by xiyichen** [YuelangX/Multiview-3DMM-Fitting#2]
Thanks for the work and code release!
I tested it on a custom multi-view dataset with ground truth camera parameters. Using the BFM model, I am able to get desired results, but using FLAME 2020 (with the same camera parameters and landmarks), the resulted mesh looks very distorted.
BFM result:
![vis_1_bfm](https://github.com/YuelangX/Multiview-3DMM-Fitting/assets/50854238/47e73be7-a4ac-4c5d-8aed-7a8b5f86fe8f)
FLAME result:
![vis_1_flame](https://github.com/YuelangX/Multiview-3DMM-Fitting/assets/50854238/6324ca00-9b2a-4139-9403-3ba7aae96433)

I wonder if you used a different FLAME version. I also tried 2019 but it's also not working.

**Comment by YuelangX** [comment]
The default parameter setting is for FLAME 2017. Maybe you can simply try to modify the weight of regular loss to get better results.

**Comment by xiyichen** [comment]
Increasing both regularization weights to 1e-5 indeed solves the problem. Thank you!
