### ISSUE TITLE
About Visualization 

### ISSUE THREAD

**Issue by jeb0813** [YuelangX/Multiview-3DMM-Fitting#4]
Hi @YuelangX , I successfully get fitting results from videos, but I have difficulty in visualization.
How to get visualization results like  `gifs/` .
Vertices can be exported to mesh and view in external Viewer, but how to project with a camera to get a mask with actual positon in image like your results?

Thank you!

**Comment by YuelangX** [comment]
Have you set visualize as True in the config file? The visualization results will be saved.

**Comment by jeb0813** [comment]
whoops, it was set to False due to OpenGL problem.
Many thanks!
